server:
  port: 8082

spring:
  application:
    name: recipe-book-server
  datasource:
    url: jdbc:postgresql://${RB_DB_HOST}:5432/${RB_DB}
    username: ${RB_DB_USER}
    password: ${RB_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    clean-on-validation-error: false
recipe-book:
  default-admin-password: ${RB_DEFAULT_PWD}
