name: Pull Request Test

on:
  pull_request:
    branches: [ main ]

concurrency: 
  group: pr-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run Tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check
    
